### ISSUE TITLE
jekyll-plantuml build doesn't work in WSL2 environment due to Liquid exception unknown tag 'plantuml`

### ISSUE THREAD

**Issue by dragondive** [yegor256/jekyll-plantuml#20]
**What I'm trying to do**

Use plantuml in Jekyll blog to generate a diagram, using the below command:

```bash
bundle exec jekyll serve --watch --force-polling --livereload
```

**My source codes**

* _yyyy-mm-dd-title_.md file:

  ```markdown
  {% plantuml %}
  [First] - [Second]
  {% endplantuml %}
  ```

* _config.yml file:

  ```yml
  plugins:
    - jekyll-plantuml
  ```

* Gemfile file:

  ```
  gem 'jekyll-plantuml', '~> 1.3', '>= 1.3.4'
  ```

**Software versions**

- OS: Ubuntu 20.04.5 LTS (using WSL2 on Windows 11)
- Ruby: 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]
- Jekyll: 3.9.2
- Bundler: 2.4.8
- Liquid: 4.0.3

**Expected behaviour**

Jekyll build generates the HTML pages properly with the PlantUML diagrams included

**Actual behaviour**

Build crashes with following error:

```bash
  Liquid Exception: Liquid syntax error (line 1): Unknown tag 'plantuml' in /mnt/c/WORK/dragondive/dragondive.github.io/docs/_posts/2023-03-11-plantuml-in-jekyll-blog.md
jekyll 3.9.2 | Error:  Liquid syntax error (line 1): Unknown tag 'plantuml'
/home/dragondive/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/document.rb:23:in `unknown_tag': Liquid syntax error (line 1): Unknown tag 'plantuml' (Liquid::SyntaxError)
```

**What I have tried so far**

- Run plantuml "standalone" in the same environment [x]

```
plantuml foo.puml
```

This properly generates the `foo.png` with the specified diagram. It confirms that plantuml is properly installed and working.

What else can I try to fix this problem?

---

Make sure the title of the issue explains the problem you are having. :white_check_mark: Also, the description of the issue must clearly explain what is broken, not what you want us to implement. :white_check_mark: Go through this checklist and make sure you answer "YES" to all points:

  - You have all pre-requisites listed in README.md installed :white_check_mark:
  - You are sure that you are not reporting a duplicate (search all issues) :white_check_mark:
  - You say "is broken" or "doesn't work" in the title :white_check_mark:
  - You tell us what you are trying to do :white_check_mark:
  - You explain the results you are getting :white_check_mark:
  - You suggest an alternative result you would like to see :white_check_mark:

This article will help you understand what we are looking for: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html :white_check_mark:

**Comment by yegor256** [comment]
@rultor release, tag is `1.4.1`

**Comment by yegor256** [comment]
@rultor release, tag is `1.4.1`

**Comment by yegor256** [comment]
@dragondive try version 1.4.1, I believe it should work just fine. You can see the test suites that prove it: https://github.com/yegor256/jekyll-plantuml/tree/master/test-jekylls
