### ISSUE TITLE
render is broken: undefined method "exists" in jekyll-plantuml-svg.rb when running on Ruby 3.2.2

### ISSUE THREAD

**Issue by TomConner** [yegor256/jekyll-plantuml#21]
Problem:

With a site on jekyll 4.3.2 with the jekyll-plantuml plugin, on ruby 3.2.2, during `bundle exec jekyll build` or `serve` I get

```
_plugins/jekyll-plantuml-svg.rb:53:in `render': undefined method `exists?' for File:Class (NoMethodError)

      if !File.exists?(uml) or !File.exists?(svg)
              ^^^^^^^^
Did you mean?  exist?
```

In Ruby 2.7.8 ([doc](https://ruby-doc.org/2.7.8/File.html#method-c-exists-3F)), the `exists` method was available but marked deprecated. In Ruby 3 ([doc](https://ruby-doc.org/3.2.2/File.html)), `exists` is gone but `exist` seems equivalent.

Suggestion:

Replace `exists` with `exist` throughout jekyll-plantuml.

Checklist:
✅ - You have all pre-requisites listed in README.md installed 
✅ - You are sure that you are not reporting a duplicate (search all issues)
✅ - You say "is broken" or "doesn't work" in the title
✅ - You tell us what you are trying to do
✅ - You explain the results you are getting
✅ - You suggest an alternative result you would like to see

**Comment by yegor256** [comment]
@rultor release, tag is `1.4.0`

**Comment by yegor256** [comment]
@TomConner please, try version 1.4.0, should work fine

**Comment by TomConner** [comment]
Yes 1.4.1 works great. Thanks!
