### ISSUE TITLE
Using standard syntax

### ISSUE THREAD

**Issue by mcondarelli** [yegor256/jekyll-plantuml#28]
Is there any reason preventing usage of (de facto) standard syntax for PlantUML
inclusion using fencing?

I mean: Why use
~~~
{% plantuml %}
@startuml
...
@enduml
{% endplantuml %}
~~~
instead of:
~~~
```puml
@startuml
...
@enduml
```
~~~
Could this be considered in future updates?

**Comment by yegor256** [comment]
@mcondarelli I believe, both options would work just fine. I just added a test for it: 7366d3b
