### ISSUE TITLE
Invoke plantuml using code-block syntax

### ISSUE THREAD

**Issue by noamtamim** [yegor256/jekyll-plantuml#9]
Not sure if Jekyll plugins can do it, but worth the try. It would be awesome to be able to use this syntax for invoking PlantUML:

```plantuml
Alice->Bob: Hello!
```

Just like regular code. It makes the markdown file very readable even when not rendered by Jekyll. And it's less to type.

**Comment by noamtamim** [comment]
I have no idea how to escape the code block. My intention is to be able to use plantuml just like a language highlighter -- enter three backticks followed by `plantuml`, followed by the plantuml code.

**Comment by davvd** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@noamtamim see how I'm using it in my blog:  https://raw.githubusercontent.com/yegor256/blog/master/_posts/2016/mar/2016-03-30-jare-instant-free-cdn.md

```
{% plantuml %}
skinparam componentStyle uml2
Browser -right-> [Edge]
[Edge] -right-> [Central]
[Central] -right-> [Origin]
{% endplantuml %}
```

This is how it looks in HTML: http://www.yegor256.com/2016/03/30/jare-instant-free-cdn.html

**Comment by yegor256** [comment]
@noamtamim or I didn't understand your question?

**Comment by noamtamim** [comment]
It wasn't a question, but a feature request. 
When I want to put Java code in markdown, I write three backticks followed by the word "java". I then write the code block.
I want to use the same logic for plantuml. Type three backticks, then "plantuml" and then the plantuml "code".

Is it possible?

**Comment by yegor256** [comment]
@noamtamim nope, it's not possible in Liquid: https://shopify.github.io/liquid/
